apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-hello-world
  description: Testing repo to check the backstage catalog
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: guests
