name: Python Run Script
on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: string
        description: 'the env'
      tier:
        required: true
        type: string
        description: 'the tier'
env:
  ENV: ${{ inputs.env }}
  TIER: ${{ inputs.tier }}

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ];
            then
              pip install -r requirements.txt
          fi

      - name: Run script
        id: run_script
        run: |
          python3 main.py
      - uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          blueprint: "python-hello-world-job"
          properties: '{ "script": "main.py", "status": "${{ steps.run_script.outcome}}" }'
          

        
